### ISSUE TITLE
Webauthn adding new key for service bug

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#103]
### Expected behavior
If you disconnect your mooltipass during the webauthn authentication(adding new key) it should stop if bluetooth is not enabled.
### Actual behavior
If you disconnect your mooltipass during the webauthn authentication(adding new key) you can save the "key" and nothing is displayed on the website. If you try to add a key again nothing happens on the mooltipass.
### Step by step guide to reproduce the problem
1) connect your mooltipass with usb
2) insert your smartcard and pin
3) go to https://demo.yubico.com/webauthn and create a demo account
4) add a new key
5) wait 5 seconds after you get the message if you want to add the "credential"
6) unplug the mooltipass and accept the credential
7) when you repeat step 4 nothing happens on the mooltipass

### Firmware Version
AUX MCU version:  0.18
Main MCU version:  0.22

### Operating System
- Windows 10 Pro

**Comment by limpkin** [comment]
@0x0ptr : i can have a look as well, up to you :)

**Comment by limpkin** [comment]
as always, thanks for these awesome bugs!
