### ISSUE TITLE
Webauthn crashes Mooltipass Mini BLE

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#104]
### Expected behavior
If you disconnect your mooltipass during the webauthn authentication(adding new key) nothing should happen.
### Actual behavior
If you disconnect your mooltipass during the webauthn authentication(adding new key) the mooltipass crashes right after that.
### Step by step guide to reproduce the problem
1) connect your mooltipass with usb
2) insert your smartcard and pin
3) go to https://demo.yubico.com/webauthn and create a demo account
4) add a new key
6) unplug the mooltipass right after that
7) You can't do anything anymore. 

### Firmware Version
AUX MCU version:  0.18
Main MCU version:  0.22

### Operating System
- Windows 10 Pro

**Comment by limpkin** [comment]
just to be clear... at what point should I disconnect the unit? during the prompt?

**Comment by ThunderKing54** [comment]
right when the prompt appear

**Comment by limpkin** [comment]
prompt on the device, correct?

**Comment by ThunderKing54** [comment]
On the "Add New Credential" prompt on the device. Don't press anything. Unplug the usb cable right after the prompt is displayed.

**Comment by limpkin** [comment]
holly molly that was a tough one that required me to change the internal logic... I'll have to send you a new firmware for you to continue your testing :D
