### ISSUE TITLE
Enter Pin arrows missing

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#106]
Here is a good one again ;)
### Expected behavior
If you insert your card and scroll up a tiny bit the animation arrow should not disappear.
### Actual behavior
If you insert your card and scroll up a tiny bit the animation arrow disappear.
### Step by step guide to reproduce the problem
1) enter your smartcard
2) press the scroll wheel for 2  seconds until the Mooltipass Mini BLE main window appear
3) press the scroll wheel and move the scroll wheel one klick up right when the prompt "Enter Your PIN" appears. This is tricky to reproduce. I spend 2 minutes to take the picture again 😆  
4) The arrows above and under the first digit disappear.

### Firmware Version
AUX MCU version:  0.19
Main MCU version:  0.23

### Operating System
- Windows 10 Pro

![image0](https://user-images.githubusercontent.com/58223763/79302857-ca069780-7eed-11ea-8db8-d97023abc7eb.jpeg)

**Comment by limpkin** [comment]
thanks a lot :)
