### ISSUE TITLE
Service name diplayed incorrectly

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/minible#108]
### Expected behavior
Service/domain names should diplay consistently.
### Actual behavior
If the password begins with :  <- (colon), at the credential recall the service name is shown the a trailing / <- (slash).
If the service/domain  is in the favorites it also displays the name incorrectly there. With a slash added to the end.
### Step by step guide to reproduce the problem
Add a credential to the device for example:
Service name: test_site
Login: leave blank
Password: :test_passwod

### Firmware Version
AUX MCU version:  0.19
Main MCU version:  0.23

**Comment by limpkin** [comment]
thanks for the bug finding!
