### ISSUE TITLE
too short underline headline inside keyboard layout for bluetooth

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#112]
### Missing feature
Calculate the length of the underline depending on the with of the headline. If you go into the keyboard layout menu for bluetooth the underline is too short. 

### Justification
It clearify the headline

### Workarounds
there are no workaournd at the moment

**Comment by limpkin** [comment]
which underline are you talking about? :) do you have a picture? not sure to follow

**Comment by ThunderKing54** [comment]
![55BF21AA-CA8E-4EBC-8083-DD90F366D089](https://user-images.githubusercontent.com/58223763/80355246-1f409280-8878-11ea-951f-1fd41e9158d7.jpeg)
![5D41CF21-2612-4196-8BA8-D5A83F2D20B5](https://user-images.githubusercontent.com/58223763/80355262-25367380-8878-11ea-86aa-aedcde00f7c7.jpeg)
![6803A04F-7B33-4FC6-8EC9-AA35CE576491](https://user-images.githubusercontent.com/58223763/80355275-28316400-8878-11ea-80d6-8e78c313bc52.jpeg)

**Comment by ThunderKing54** [comment]
"Selected Service" is fine(last picture)
But the underline for "Select USB Layout" and "Select Bluetooth Layout" is too short for my opinion. The underline length should by calculated by the headline text length

**Comment by limpkin** [comment]
Ohhhh that's a nice touch.

**Comment by ThunderKing54** [comment]
😄

**Comment by limpkin** [comment]
fixed! also fixed that "bluetoth" typo
thanks a lot :)

**Comment by ThunderKing54** [comment]
Didn't noticed the "bluetoth" typo 😆. It is the tipical "The Significance of Letter Position in Word Reconition"
