### ISSUE TITLE
Slowly click-scrolling credentials hard-resets the device

### ISSUE THREAD

**Issue by Arffeh** [mooltipass/minible#113]
### Expected behavior
While actively clicking down the scroll-wheel and scrolling successfully through the login credentials, 5-second hard-reset timer shouldn't be counting.

### Actual behavior
Timer triggers while click-scrolling through credentials, If I'm too slow and the 5 second timer expires, the MP-BLE hard resets.

### Step by step guide to reproduce the problem
  - Enter PIN
  - Select Login
  - Hold down scroll wheel
  - Start slowly scrolling through your lovely massive set of credentials
  - After5 seconds the device will trigger a reset from holding down the scroll wheel too long.

### Firmware Version
AUX MCU version:  0.20
Main MCU version:  0.24

### Operating System
Arch Linux (not relevant)

**Comment by limpkin** [comment]
It's actually a 10 seconds timer... perhaps I should extend it to 15 seconds as pushing without scrolling for 10 seconds straight could get tricky...

**Comment by Arffeh** [comment]
If it's 10, then I must be having a slightly different problem. 
I just used a stopwatch, it happens at 6 seconds. Tested multiple times.

6 is oddly specific.

**Comment by limpkin** [comment]
You're indeed perfectly right!
https://github.com/mooltipass/minible/blob/master/source_code/main_mcu/src/platform_defines.h#L422

Will increase it to 10 and mark it fixed :), feel free to reopen if you feel that it is still to short :)
