### ISSUE TITLE
Bluetooth pairing: change abort message to "Pairing canceled by User"

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#115]
### Missing feature
If you abort the pairing between the Mooltipass and the other bluetooth device it should not display the message "Couldn't Pair with Device" It should display the message "Pairing canceled by User"
### Justification
The current message could confuse the people. 
### Workarounds
There are no workarounds at the moment. 
###Step by Step
1) go to bluetooth menu
2) start the pairing process
3) abort the pairing process by pressing the scroll wheel for 3 seconds

**Comment by ThunderKing54** [comment]
If the Pair ends by a timeout it is fine thate the message "Couldn't Pair with Device" appears.

**Comment by limpkin** [comment]
I like you!

**Comment by ThunderKing54** [comment]
<3
