### ISSUE TITLE
Database File Management stuck after disconnect USB

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#116]
And it happen again 🤣 
### Expected behavior
If you disconnect your mooltipass during Database Management(Files) it should stop the Database Management if Bluetooth is not enabled and paired.
### Actual behavior
If you disconnect your Mooltipass during Database Management(Files) it is stuck inside the Database Management Animation.
### Step by step guide to reproduce the problem
1) connect your Mooltipass with USB
2) enter your smartcard and pin
3) go to Moolticute "Files" page
4) press the button Enter Files Management Mode
5) disconnect your Mooltipass
6) Mooltipass is Stuck inside the Management Mode
### Moolticute Version - If Involved
v0.43.14
### Firmware Version
AUX MCU version:  0.20
Main MCU version:  0.24

### Operating System
Mention if you are using either:
- Windows 10 Pro

**Comment by limpkin** [comment]
oh indeed! I'll fix this tonight :)

**Comment by ThunderKing54** [comment]
Thank you :)
