### ISSUE TITLE
Turn off Device prompt won't appear anymore

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#127]
### Expected behavior
When you pressed the scrollwheel a bit longer a prompt appeared if you want to turn off your device.
### Actual behavior
When you pressed the scrollwheel a bit longer a prompt appeared if you want to turn off your device.  But right now this prompt will not appear anymore.
### Step by step guide to reproduce the problem
1) remove smartcard or got to the login screen
2) press the scrollwheel for 3-5 seconds
3) a shut down prompt should appear

### Firmware Version
AUX MCU version:  0.24
Main MCU version:  0.30

### Operating System
- Windows 10 Pro

**Comment by limpkin** [comment]
are you sure about this issue? 
the device won't switch off if connected through USB FYI
