### ISSUE TITLE
Add wheel "click shortcuts" for BLE actions

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/minible#128]
### Missing feature

wheel "click shortcuts" for BLE actions

### Justification
Enabling/Disabling Bluetooth, switching from device to an other could be thing that could happens quite frequently. It would be nice to be able to do these action with some kind of wheel click shortcut. For example a double-click could execute the disconnect action (and therefore reconnect to other device). A triple-click could enable/disable bluetooth.

### Workarounds

Use the menu options

**Comment by limpkin** [comment]
I'm thinking of these when in the main menu:
- wheel press - scroll up - scroll down (still pressed) to disconnect
- wheel press -scroll down - scroll up (still pressed) to enable / disable bluetooth

would that work?

**Comment by elendil-software** [comment]
Yes, probably

**Comment by elendil-software** [comment]
I think this issue can be closed.

**Comment by limpkin** [comment]
sweet!
