### ISSUE TITLE
Option to sort "Login" menu by recently used

### ISSUE THREAD

**Issue by ilmiont** [mooltipass/minible#145]
### Missing feature

It would be useful to have the ability to sort the on-device "Login" menu by recently used, instead of the default unchangeable alphabetical order.

### Justification

This would be extremely useful when accessing the same credential in quick succession.

For example, when working in a shell:

```
ssh james@foobar
sudo foobar
```

Currently, scenarios like this require you to:

0. Unlock the Mooltipass.
1. (Command 1) Login.
2. (Command 1) Scroll down the list...
3. (Command 1) Select the credential, approve to type the password.
4. (Command 2) Login.
5. (Command 2) Scroll down the list...
6. (Command 2) Select the credential, approve to type the password.

It can end up taking 15+ seconds, in my experience, to complete this procedure... and then after a few minutes, I might find my superuser elevation has expired, and I need to elevate myself again...

Were the menu to be sorted by recently used, the above would be much reduced, as "Command 2" onwards would consist of Login > (last used credential automatically selected) > approve to type the password.

### Workarounds

This functionality partially overlaps with the existing "Favourites" menu. However, I don't consider Favourites to be a suitable alternative, as if you have a large number of favourites, the situation really is no different to that described above (in fact, it is worse really, as you must first scroll the main menu to the favourites section, instead of pressing the wheel to enter the login menu).

**Comment by limpkin** [comment]
Hello all!
After giving it some thought and given our memory limitations I settled on a compromise that I hope you'll find OK: a setting that will allow credential sorting in the favorites menu. I'm also thinking of perhaps making another setting that makes "favorites" as the default menu item.
Please also note that I also recently added another setting that allows remembering the last accessed credential in the login menu. 
Let me know what you think!
