### ISSUE TITLE
Option to disable UI animation

### ISSUE THREAD

**Issue by ilmiont** [mooltipass/minible#146]
### Missing feature

The ability to disable UI animation is provided by many applications and operating systems.

The Mini BLE makes extensive use of animation in its UI; while beautiful, these animations also make the UI feel slower to use - this is naturally a personal opinion.

Having the *option* to disable animation would enable more "rapid-fire" use of the BLE, even if it's only a perceived improvement in performance.

### Justification

The Mooltipass should be convenient and not just secure.

Waiting for animations, or *feeling like* you're waiting for animations, reduces the convenience of the device if you need to login quickly.

"Reduced animation" or "reduced motion" modes are also increasingly prevalent within the wider digital ecosystem (e.g. `prefers-reduced-motion` CSS media query); it also has the extra benefit of potentially making the device more accessible to individuals who have problems perceiving motion or who experience nausea as a result.

https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html

### Workarounds

None.

**Comment by limpkin** [comment]
just implemented in f09570efe3fbb131a1c502dc6677510a08b52df1:)
