### ISSUE TITLE
When active category is "All categories", Favorites menu should display all favorites

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/minible#147]
### Expected behavior

When active category is set on "All categories", Favorites menu should display all favorites

### Actual behavior

Only favorites without category are displayed

### Step by step guide to reproduce the problem

Configure a favorite and assign a category. 
On the Mooltipass set category on "All categories". 
Enter in Favorite menu. 
The favorite is not displayed.

### Firmware Version
AUX MCU version:   0.28
Main MCU version:  0.34

### Operating System
Mention if you are using either:
- Windows 10

**Comment by limpkin** [comment]
how did we miss that.... awesome find!!!!
