### ISSUE TITLE
Option to shutdown device when USB disconnected

### ISSUE THREAD

**Issue by ilmiont** [mooltipass/minible#149]
### Missing feature

Moolticute has a "Device Lock on USB Disconnection" option.

I propose a "Device Shutdown on USB Disconnection" option too.

### Justification

Sometimes I use the device purely in USB mode and forget that disconnecting won't shut it down, which could cause battery drain.

This would also ensure the Mooltipass is powered down whenever the USB host device powers down.

Adding this option ensures the device is shutdown after use and is akin to the behaviour of the Mini.

### Workarounds

None.

**Comment by limpkin** [comment]
neat idea!
