### ISSUE TITLE
Enter _unlock_ service password right away

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#154]
### Missing feature
There should be an option that the _unlock_ service inserts the password right away after selecting the right account.
### Justification
It takes so much time when you use this feature.
1) insert smartcard 
2) enter pin
3) select right windows account
4) accept the prompt to enter the password.

Or it is one step for me if I type in the password manually
### Workarounds
Type in the password by hand and not with the mooltipass.

**Comment by limpkin** [comment]
so that would be only in the case of when the unlock service has multiple credentials?

**Comment by ThunderKing54** [comment]
right
