### ISSUE TITLE
Use of long click to power on the MiniBLE

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/minible#156]
### Missing feature

Instead of a simple short click to power on the MiniBLE, another combination should be used (long click, double click, ...) 

### Justification

When put in a bag, it can happens that it powered on by itself if it is moving in the bag, pushed against other item in the bag, etc.

### Workarounds

N/A

**Comment by limpkin** [comment]
I'm afraid that's a hardware design choice... nothing i can do about that :/

**Comment by elendil-software** [comment]
Ok, no problem
