### ISSUE TITLE
Inform unlocked not received when user starts to enter PIN right after connection

### ISSUE THREAD

**Issue by deXol** [mooltipass/minible#186]
### Expected behavior
`_unlock_` credential is not prompted after connecting device and computer is unlocked

### Actual behavior
When the user starts to enter PIN right after connected device it will prompt `_unlock_` (If I wait a few seconds after connection it works as expected)

### Step by step guide to reproduce the problem
(In MC need implementation from https://github.com/mooltipass/moolticute/pull/718)
1. Have an `_unlock_` user 
2. Enable Lock Unlock Feature in MC's Device Setting page
3. Connect Device
4. Start to enter PIN instantly

### Moolticute Version - If Involved
Latest with https://github.com/mooltipass/moolticute/pull/718 in it

### Firmware Version
AUX MCU version:  0.37
Main MCU version:  0.44

### Operating System
- Ubuntu 20.04
- Mac OS
- Windows 10

**Comment by limpkin** [comment]
fixed in https://github.com/mooltipass/minible/commit/eeeac7ceb0fb94e4bddd2ef0810bcedde89443f2
