### ISSUE TITLE
Device freezing on cable disconnect

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/minible#208]
The device freezes with a black screen when I remove the power cable, and get a # 005 error

Steps to reproduce:
* Turn on the Bluetooth
* Unplug, power off the device and remove the smart card
* Plug in the USB cable
* Insert the smart card
* At the Enabling Buetooth message remove the USB cable
* The device screen turns off, when it turns on it gives the 005 error

**Comment by elendil-software** [comment]
I confirm. I can add I got "Many Failed Connections" massage.

**Comment by limpkin** [comment]
@WebmasterTD That's a free mooltipass mini BLE for you! send me an email with a link to that issue please? :)
