### ISSUE TITLE
Call credentials with wrong side of smartcard

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#211]
This is a funny bug mathieu ;D
### Expected behavior
if you unplug your smartcard the mooltipass should instantly lock itself
### Actual behavior
the mooltipass is not locked after I unplug the mooltipass during the message "Einige Buchstaben konnten nicht geschrieben werden"
### Step by step guide to reproduce the problem
1) connect your Mooltipass to your iPhone with Bluetooth
I think it works as well with USB
2) go to "Login" and select any login credential or service names wich contain special letters replaced with "????"
3) Accept typing the password and username
4) unplug the smartcard during the message "Could not write all characters" and turn it back in the wrong side around.
5) you should see the credentials accepting message again
6) Accept it again. It should display the credentials. After that it will lock itself

### Firmware Version
AUX MCU version:  0.46
Main MCU version:  0.55

### Operating System
Mention if you are using either:
- iOS 14.2

![05CA97B5-A343-4EEE-8329-10E4F6E69A36](https://user-images.githubusercontent.com/58223763/102419516-2d5a4380-4000-11eb-9ef4-592bc01b1bc0.jpeg)
![C0CFF33E-B423-450A-8099-BBFC0A0210C8](https://user-images.githubusercontent.com/58223763/102419524-31866100-4000-11eb-982e-332013a3d641.jpeg)

**Comment by limpkin** [comment]
wow that was a fun one indeed!
