### ISSUE TITLE
Error "#002" after usb disconnect during Bluetooth pairing

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#214]
### Expected behavior
if you unplug the usb cable during pairing it should prompt an error message or cancel the pairing.
### Actual behavior
if you unplug the usb cable during pairing the mooltipass freeze and wake up with #002 Contact Support in some cases.
### Step by step guide to reproduce the problem
1) enter smartcard and pin
2) Connect your Mooltipass to usb
3) go to bluetooth and start pairing with a new device
4) Connect your phone bluetooth to the miniBLE
5) Accept the pairing code with six zeros 
6) Now the miniBLE trys to pair with your smartphone
7) disconect the usb cable during the prompt "Pairing with device"
8) The mooltipass freeze
9) After some time the message #002 Contact Support appear. 

### Firmware Version
AUX MCU version:  0.47
Main MCU version:  0.56

### Operating System
- Windows 10
- iOS 14.2

**Comment by limpkin** [comment]
fixed by https://github.com/mooltipass/minible/commit/4d3445735430125009c0765f20ffee5a81b36bad , another free mini BLE for @ThunderKing54 !
