### ISSUE TITLE
"Please remove the card" message when connecting device to computer.

### ISSUE THREAD

**Issue by Timandrias** [mooltipass/minible#23]
### Expected behavior

I expect the device no to randomly ask me to please remove the card.

### Actual behavior

When I connect the device to the computer, sometimes asks me to remove the card. If I forget to input the pin, eventually asks me to remove the card.

### Step by step guide to reproduce the problem

Turn Off mooltipass.
Turn On mooltipass.
Connect to computer. (Sometimes, here it asks to remove the card)
Do not input pin. Wait some minutes.
There you go. "Please remove the card"

### Moolticute Version - If Involved

v0.42.5-testing

### Operating System
- Windows 10

**Comment by limpkin** [comment]
solved in 7cb6b8f49d139d7b8d65a62e12b41b09399ba844
