### ISSUE TITLE
Multiple BLE Devices

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/minible#236]
I was lucky enough to have two Mini BLE's arrive today. I paired the first one with a number of devices. However, I was unable to pair the second device. It almost appears as if the computer or phone can't see the second device, or sees it as the first device and gets confused. Is this a known issue?

**Comment by limpkin** [comment]
that shouldn't happen.... can you disable the bluetooth interface on the first one and check that your computer sees the second one?

**Comment by CubeCentral** [comment]
I am having the same issue.  I received both of my Mini BLEs yesterday and one of them I am able to pair with laptop, desktop, phone (it's a black one)  The other one I cannot pair with anything.  It is not seen at all.  The other (black) Mini BLE was nowhere near.  I've tried a desktop, laptop, and phone with no luck.  (it's a green one).  I was just looking for a tool to flash firmware on here, as I am out of ideas.

**Comment by limpkin** [comment]
@CubeCentral is it a green device as well? could you send us a message at support[at]themooltipass[dot]com?

**Comment by RChadwick7** [comment]
It appears one of mine is not working either. The first one shows up as soon as I turn Bluetooth on, but I turned it off, and turned it on on my second device, and even put it in pairing mode, but none of my devices ever see it. I got a Gray and Black. The Gray works, the Black does not.

**Comment by CubeCentral** [comment]
> 
> 
> @CubeCentral is it a green device as well? could you send us a message at support[at]themooltipass[dot]com?

I have, and I have also spoken with you on IRC.  Thank you for your help!

**Comment by limpkin** [comment]
that was a hw issue
