### ISSUE TITLE
Database model documentation is incomplete

### ISSUE THREAD

**Issue by gmarcusm** [mooltipass/minible#240]
### Expected behavior

Documentation on entries like **TOTP** or **note** child nodes in https://mooltipass.github.io/minible/database_model

### Actual behavior

`TOTP_cred_node_t `and `NODEMGMT_NOTES_DATA_TYPE_ID` exist on https://github.com/mooltipass/minible/blob/83c3d3198c60ef2e7c5e8c72d527b1472d72cd82/source_code/main_mcu/src/NODEMGMT/nodemgmt.h

but no documentation is available.

### Step by step guide to reproduce the problem

check the files, search, not found.

**Comment by limpkin** [comment]
fixed and updated to the newly created wiki page: https://github.com/mooltipass/minible/wiki/Mooltipass-Database-Model
