### ISSUE TITLE
Mini BLE freezing on manual credential input with no connected device

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/minible#250]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
It doesn't freeze when trying to manually input credentials when no device is connected

### Actual behavior

It hard freezes, I can't seem to do anything, screen stays on, button animation is frozen, controls are not responding

### Step by step guide to reproduce the problem

1. Connect BLE via bluetooth
2. let it sit for a few hours so that it disconnects automatically
3. manually select login
4. select the first item on the list
5. confirm login input

### Firmware Version
AUX MCU version:  what ever it shipped with
Main MCU version:  what ever it shipped with

### Operating System
Mention if you are using either:
- MacOS  

8<------------------------ END BUG REPORT -------------------------------------

Edit: It did only unfreeze after the battery ran out of juice

**Comment by limpkin** [comment]
fairly sure https://github.com/mooltipass/minible/commit/b26bf79c748382d71d764a878afd2d4a435ad6d9 fixes it, but keeping it open in case.

**Comment by limpkin** [comment]
@KDederichs could you get in touch with us (support at themooltipass dot com) so we can send you a firmware update to test?

**Comment by KDederichs** [comment]
Doesn't seem to crash anymore but it's also not inputting stuff via Bluetooth (using the steps outlined above).
Don't know if that's related but it's an improvement :)

**Comment by limpkin** [comment]
@KDederichs you're saying you can't use manual credential recall? :/

**Comment by KDederichs** [comment]
No, it's still working on cable and I assume after after reconnecting the BT connection?
Just right after the scenario that crashed it previously it didn't seem to transmit data via BT

**Comment by limpkin** [comment]
could you restart your computer? there's a well known issue on macOS that after first pairing, characters can't be typed :/

**Comment by limpkin** [comment]
how the new firmware update performing? should we close this?

**Comment by KDederichs** [comment]
yeah seems to be working fine on my end, I didn't experience any freezing yet so I'll just go ahead and close this one :)

**Comment by limpkin** [comment]
nice :)
