### ISSUE TITLE
Extremely short battery life.

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/minible#254]
I'm currently staying in a hotel for another week, and I suspect this may be related.

It appears that I get battery life of about 8 hours or less, when in standby. It happens when it's paired to my phone, but appears to happen when it's not as well. A few times, I noticed the display said 'Too Many Connections'. I'm surrounded by Bluetooth at the moment. Maybe that is causing the issue? Perhaps one of the residents here is trying to connect to my Mini? I tried turning off Bluetooth, and battery life seemed fine. Are there any experiments I can try, or logs to see, to help narrow down the issue?

**Comment by limpkin** [comment]
The "too many connections" message actually indicates the root cause: some device is actively trying to connect to your Mini BLE, without success. This happens because this device has stored pairing data that doesn't exist anymore on your mini BLE (maybe because you deleted pairings?).
