### ISSUE TITLE
Caps Lock detection

### ISSUE THREAD

**Issue by Timandrias** [mooltipass/minible#26]
## Missing feature
Detecting when Caps Lock is enabled. 

### Justification
If the computer is in caps-lock, the device doesn't detect it and outputs a wrong password.
Then proceeds to detect the wrong password as a new login.

### Workarounds
Just checking that Caps Lock is disabled, but half of the time my computer login password is all caps, and this comes up regularly.

**Comment by limpkin** [comment]
duplicate of #174
