### ISSUE TITLE
FIDO2: Add support for allow list with more than 1 credential

### ISSUE THREAD

**Issue by 0x0ptr** [mooltipass/minible#269]
8<------------------------ FEATURE REQUEST ------------------------------------
### Missing feature
Handle FIDO2 allow list with more than 1 credential

### Justification
Specification and use cases requires this.

### Workarounds
No

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by limpkin** [comment]
@0x0ptr i just made an attempt at implementing it... given the (hum) challenging nature of testing that use case, would you be able to try it? with 2, 3, 4 credentials? :)

**Comment by limpkin** [comment]
implemented :)
