### ISSUE TITLE
update minible from bundle verison 2 to 3 using 0 to 3 firmware

### ISSUE THREAD

**Issue by GeekAnnoyed** [mooltipass/minible#275]
Ive just got an email from you and downloaded the firmware
but I noticed it's expecting version 0 not my ble's current version of 2
I got the 2 update after emailing you from the main mooltipass website

is it safe to apply this update?

Many thanks

![image](https://user-images.githubusercontent.com/822758/126465559-204e9fa2-8d9e-42a9-ad28-1683296306fa.png)

**Comment by limpkin** [comment]
it is! but you'll need another password :). 
Can you send me a private email?
BTW: please update your moolticute version :)

**Comment by schlomie** [comment]
Hi @limpkin 

About two weeks ago, I sent an email to support@themooltipass.com asking about this very issue - but going from 0 to 4.  The password on my bundle upgrade file does not work.

Please advise.  Thank you.

**Comment by limpkin** [comment]
@schlomie could you send us another message again? it seems we missed your message :/

**Comment by schlomie** [comment]
Sent - thanks!
