### ISSUE TITLE
Periodically showing error #002

### ISSUE THREAD

**Issue by KDederichs** [mooltipass/minible#285]
### Expected behavior
No Errors

### Actual behavior
It does show error # 002 periodically and then switch back to the menu it just suddenly started and I'm not sure what's up with taht.

### Step by step guide to reproduce the problem
No clue

### Firmware Version
AUX MCU version:  0.62
Main MCU version:  0.73

### Operating System
- MacOS

**Comment by limpkin** [comment]
a firmware update will fix that :)
have a look at themooltipass.com/updates :)

**Comment by KDederichs** [comment]
Hmm not sure that's going through seems to be stuck on Starting upload bundle file for like 5 minutes now

**Comment by KDederichs** [comment]
(the 002 error also pops up in the Remove the card screen)
