### ISSUE TITLE
Login Prompt Settings should display current active value

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/minible#29]
### Expected behavior

Settings like "Credential Display Prompt?", "Prompt When Login In?", etc. should display current active value and not preselect the "Enabled" state.

### Actual behavior

The mentioned options always show the state "Enabled", even if the option is actually disabled 

### Step by step guide to reproduce the problem

1. Enter in one of the settings
2. Disable the setting
3. Enter the same setting again
4. "Enabled" is selected

Regards,

Julien

**Comment by limpkin** [comment]
good idea!
