### ISSUE TITLE
mooltipass.github.io/minible/ site appears to be missing many sections now

### ISSUE THREAD

**Issue by dragon788** [mooltipass/minible#302]
### Expected behavior
The database model and other pages should be visible/available.

### Actual behavior
The main page only shows the Test Reports, all other pages are missing, and even some from Google search results (see database model) are returning a 404.

### Step by step guide to reproduce the problem
https://mooltipass.github.io/minible/
https://mooltipass.github.io/minible/database_model.html

**Comment by limpkin** [comment]
the documentation has been moved, and the links have been updated :)
https://github.com/mooltipass/minible, ctrl-f database, https://github.com/mooltipass/minible/wiki/Mooltipass-Database-Model
