### ISSUE TITLE
Error #003 after enabling bluetooth, can't pair any devices

### ISSUE THREAD

**Issue by johncollaros** [mooltipass/minible#305]
### Expected behavior
When enabling bluetooth the device should behave normally.

### Actual behavior
If plugged in charging, after enabling Bluetooth, and then about every 20s the error message "#003 Contact Support" is displayed.

If running from battery without charging, Error #002 is displayed and the device switches off.

The device is non-responsive for 3 s before the error is displayed.

### Step by step guide to reproduce the problem
From the menu Enable Bluetooth

### Firmware Version
AUX MCU version:  0.65
Main MCU version:  0.76

### Operating System
Mention if you are using either:
- Windows 7/10
- Debian Based distribution
- Other Linux distribution
- MacOS  

Ubuntu Linux  

Other operating systems are not supported.

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

**Comment by limpkin** [comment]
003 is indicative of a bluetooth transceiver issue. 
For the new mass production we're now changing the way we check for these so I'm going to go ahead and close this issue :)
