### ISSUE TITLE
Could not upgrade Firmware

### ISSUE THREAD

**Issue by p4ck3t0** [mooltipass/minible#313]
### Expected behavior

Successfull upload of the firmware on the device

### Actual behavior

Error Message with `Upload bundle finished with error.`

### Step by step guide to reproduce the problem

Download and Upgrade the Firmware as suggestet [here](https://mooltipass.github.io/minible/updating_your_device)

### Moolticute Version - If Involved

v0.53.7

### Firmware Version
AUX MCU version:  0.64
Main MCU version:  0.75

### Operating System

Arch Linux - moolticute package from the AUR

**Comment by limpkin** [comment]
Hello!  
Did you correctly insert the card the wrong way around?

**Comment by p4ck3t0** [comment]
Yes, I tried multiple times over some weeks and it magically worked now.

**Comment by limpkin** [comment]
that's quite odd. I'll close the bug here as we've updated thousands of devices without any issue.

**Comment by p4ck3t0** [comment]
Maybe it was not working, because I already did the same Firmware upgrade, but moolticute did still show me that my device is running on Version 3. After that I got the described error, but today it magically worked :mage_man:
