### ISSUE TITLE
#002 Contact Support after Crash (reproducabel)

### ISSUE THREAD

**Issue by Jan-NiklasB** [mooltipass/minible#320]
### Expected behavior
When pressing the wheel and scrolling back in "Login", I expected to get to the end of the Credential-List

### Actual behavior
As soon as I press the wheel and scroll back the multipass reboots and shows "#002 Contact support"

### Step by step guide to reproduce the problem
(I don't know if it matters, but regarding to #318 my multipass was also sitting in my backpack for a few weeks)
Startup the multipass
Insert the card and PIN
navigate to "Login"
Press the wheel and scroll backwards

Crash happens

### Firmware Version
AUX MCU version:  0.69
Main MCU version:  0.79
Bundle version:  7

### Moolticute Version - If Involved
0.53.7

### Operating System
Mention if you are using either:
Linux Mint 19 Cinnamon

**Comment by limpkin** [comment]
Hello there!
This is actually due to a previous generation import into the mini BLE.
Could you:
- enable developer logs in moolticute
- restart moolticute
- enter management mode
- send us the logs at support[at]themooltipass(dot)com?

Thanks!

**Comment by Jan-NiklasB** [comment]
@limpkin Mail is send ;)

**Comment by limpkin** [comment]
have you received our reply? did it fix the issue? :)

**Comment by Jan-NiklasB** [comment]
Hey,

Sorry totaly forgot to answer... I was on holidays with my girlfriend until yesterday.

I will test it asap and give you a feedback.

Thanks for your great support!

Am 7. März 2022 19:28:15 MEZ schrieb Mathieu ***@***.***>:
>have you received our reply? did it fix the issue? :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mooltipass/minible/issues/320#issuecomment-1060996373
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Jan-NiklasB** [comment]
Hey, I finally had time to test your suggestion now.

And well, what should I say, I don't really know why or how, but it seems to work...

Thanks Mathieu!

For anyone else having this problem:

After sending my debug log to Mathieu he gave me a hint to delete, save and re-add the credentials of a specific website.
After doing this the problem now seems to be gone.

Maybe @limpkin can clarify what to look for in the logs.

**Comment by limpkin** [comment]
so this issue is caused by importing old generation databases to the mini BLE. In some cases (we're not sure why) a given service is present twice in the database. When this is detected on the mini BLE (scrolling up), the device reboots itself.

**Comment by Jan-NiklasB** [comment]
Fun fact, I only im and exported databases between my devices which always had the same FW version until never loaded a older backup in a device with newer FW...

Am 17. März 2022 09:03:33 MEZ schrieb Mathieu ***@***.***>:
>so this issue is caused by importing old generation databases to the mini BLE. In some cases (we're not sure why) a given service is present twice in the database. When this is detected on the mini BLE (scrolling up), the device reboots itself.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mooltipass/minible/issues/320#issuecomment-1070510861
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by limpkin** [comment]
hmm, but you did have a mooltipass mini or original, right? :)

**Comment by Jan-NiklasB** [comment]
Nope, only mini ble

Am 17. März 2022 10:10:24 MEZ schrieb Mathieu ***@***.***>:
>hmm, but you did have a mooltipass mini or original, right? :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mooltipass/minible/issues/320#issuecomment-1070585790
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by limpkin** [comment]
Oh then that's a point of worry for us, as I'm guessing there are some
cases where moolticute might create a service during credential merging.
I'll check on our side.
