### ISSUE TITLE
Provide option to make battery charging optional when plugging the MiniBLE into a host

### ISSUE THREAD

**Issue by MaplesThroughWindows** [mooltipass/minible#321]
### Missing feature
Give users the option of enabling a feature that allows them to choose whether or not to charge the battery when plugging the Mooltipass into a host.  I would suggest that this default to 'on'.

### Justification
On Page 16, Paragraph L of the Mooltipass Mini BLE User Manual (release 25-12-2021), users are reminded that the device uses a NiMH battery, and warns:

`For maximum battery longevity, we recommend you use your device until its battery is depleted.`

For users who prefer to use the USB cable to enter passwords and manage the device, they cannot avoid charging the device every time.  This will impact the lifespan of the NiMH battery.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?
N/A

**Comment by My1** [comment]
> For users who prefer to use the USB cable to enter passwords and manage the device, they cannot avoid charging the device every time. This will impact the lifespan of the NiMH battery.

not even just prefer. fido2 for example has to be done over USB.

**Comment by hughobrien** [comment]
I find that unless plugged in the RTC for TOTP codes is often unset/out of sync. As a result mine is almost always plugged in which I know is a problem for the battery.

**Comment by spoelstraethan** [comment]
@limpkin when is the firmware with this change expected to get published?

**Comment by limpkin** [comment]
Aiming for August :)

**Comment by limpkin** [comment]
bundle v13 is available at https://beta-updates.themooltipass.com/ !
