### ISSUE TITLE
Keyboard shortcuts for Advanced tab and BLE Dev tab are not working

### ISSUE THREAD

**Issue by CodeGrammer45** [mooltipass/minible#333]
I am running MacOS Monterey 12.3, running Moolticute version 0.55.0, and I cannot get the keyboard shortcuts for the Advanced tab or the BLE Dev tab to work. These should be _Shift+Fn+Cmd+F2_ and _Shift+Fn+Cmd+F3_ respectively.

**Comment by limpkin** [comment]
Hello, 

Sorry! we need to update the user manual: new shortcuts are now shift+f2 / f3 :)

**Comment by CodeGrammer45** [comment]
Oh awesome, thank you!!
