### ISSUE TITLE
Moolticute doesn't allow firmware upgrade on MacOS 12.3.1

### ISSUE THREAD

**Issue by elonen** [mooltipass/minible#342]
### Expected behavior

Selecting update-from-bundle file (a .dmg) in Moolticute would upgrade the device.

### Actual behavior

Operating system's file selection dialog that opens doesn't allow selecting the bundle file. Rather, it **stays grayed out** as if wrong file type.

### Step by step guide to reproduce the problem

Follow firmware upgrade instructions on Moolticute and try to open the downloaded .dmg file from disk.

### Moolticute Version - If Involved

 0.55.0

### Operating System
Mention if you are using either:
MacOS  Monterey 12.3.1

**Comment by elonen** [comment]
Sorry, wrong repo, should be on Moolticute.

**Comment by limpkin** [comment]
Hello!

The downloaded update file is a .img and not a .dmg . it seems in some
cases safari will just decide to change the extension.
Could you rename the extension and try again?
