### ISSUE TITLE
Mooltipass does not type correct password

### ISSUE THREAD

**Issue by drwonky** [mooltipass/minible#346]
### Expected behavior
Mooltipass should type `Z\-dX%JE8xPf(psQ`

### Actual behavior
Mooltipass types `Z<-dX%JE8xPf(psQ`

### Step by step guide to reproduce the problem
- Set a password to `Z\-dX%JE8xPf(psQ`
- Choose the credential from the menu and confirm that it should be sent (typed)

### Firmware Version
AUX MCU version:  0.66
Main MCU version:  0.77
Bundle version:  5

### Operating System
Mention if you are using either:
- Windows 7/10
- Debian Based distribution
- Other Linux distribution
- MacOS  

Other operating systems are not supported.

Fedora 34

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

**Comment by limpkin** [comment]
Hello there!
Could you try upgrading your bundle to v8 using www.themooltipass.com/updates/, then select the "USA (Linux)" layout? :)

**Comment by drwonky** [comment]
Hi, I went through the update process but it failed with an error.  No data appears to have been sent to the Mooltipass.
I am running Moolticute v0.53.2 and it shows a password fields for firmware upload, but the update instructions online just show a `Select Bundle` button.

**Comment by drwonky** [comment]
OK, downloaded 0.55.0 AppImage and ran that, the instructions matched the application and I was able update the firmware.

**Comment by drwonky** [comment]
I updated to bundle 8 and it still fails to type the password correctly.
Typed credential:`foo	Z<-dX%JE8xPf(psQ`
From Moolicute:
![image](https://user-images.githubusercontent.com/35117150/177439095-da731726-2b31-4ffc-91e5-2af6a261d9b7.png)

**Comment by drwonky** [comment]
![image](https://user-images.githubusercontent.com/35117150/177610244-d1382409-a1d7-4ccf-8c24-0d5714ad1527.png)

**Comment by drwonky** [comment]
Your hunch seems to have paid off.  The `USA` USB keyboard layout sends the wrong scancode (see https://forums.puri.sm/t/librem-13-backslash-key-generates-less-than-symbol/2133/2 ) but if I change the layout to `USA (Linux)` it sends the correct scancode.

I'm a bit confused here, if I plug a regular keyboard into a computer and run Linux or Windows, the keyboard types the same scancodes irregardless of the OS and the scancodes result in the same output.  The scancodes are hardcoded in the ROM of the keyboard itself.  So why is Mooltipass sensitive to OS when choosing a USB keyboard layout?

I presume this means that my Mooltipass will not correctly type passwords with a backslash across platforms?  So I can't transport it to a Windows device and get the correct output?

**Comment by limpkin** [comment]
You're right that the Mini BLE could simply select the USA (Linux) by default. The current USA layout was made using the CLDR data (https://cldr.unicode.org/), which supposedly sets the standard :/.

In theory USA (Linux) should also work on Windows :)
