### ISSUE TITLE
Contact support 003

### ISSUE THREAD

**Issue by GeekAnnoyed** [mooltipass/minible#351]
Displaying message "contact support 003"
updated to beta as requested in #349 , I have a terrible memory and can't say for sure if it was happening before.

this might be related to #349 I didn't want to merge two potential issues in one report

### Step by step guide to reproduce the problem
no real steps, I had powered on the PC, went to make coffee and when I got back the miniBLE was displaying the contact message
### Firmware Version
AUX MCU version:  0.72
Main MCU version:  0.82
Bundle version:  10

### Moolticute Version - If Involved
v0.55.0
### Operating System
Mention if you are using either:
- Fedora 36

**Comment by limpkin** [comment]
003 indicates a bluetooth issue. Can you send us a private email and we'll replace your unit :)
