### ISSUE TITLE
Smart Card Question

### ISSUE THREAD

**Issue by labrys** [mooltipass/minible#357]
I'm sure this isn't the best place to post this request, but as I can't register on Tindie to ask a question (their e-mail verifcation system is currently broken), I'll post it here.  It looks like the minible uses a custom small-size smartcard.  Is there support for full size cards and any known sources for them?

**Comment by limpkin** [comment]
Hello!
The device uses AT88SC102 based smartcards, we can provide you with some if you reach out to us directly :)
