### ISSUE TITLE
The symbol ^ on the Russian keyboard is written with a space after it

### ISSUE THREAD

**Issue by EugeneRymarev** [mooltipass/minible#369]
### Expected behavior
Do not enter characters that do not exist
![image](https://user-images.githubusercontent.com/6260309/210941200-116865e5-8f0d-46ec-ad81-20ceecf44026.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/6260309/210941174-e1fa2e8c-a20a-4903-ac26-0b9315dc8b39.png)

### Step by step guide to reproduce the problem
Manual selection and entry of credentials.
A space is always after the `^` or `:` (if RUS layout) character.
`Shift + 6` on this layout
![image](https://user-images.githubusercontent.com/6260309/212556099-7d746fb6-859c-4fdb-bd2f-f8b41049396e.png)

### Firmware Version
AUX MCU version:  0.73
Main MCU version:  0.84
Bundle version:  12

### Moolticute Version
v1.00.1

### Operating System
- Windows 11 Pro (Russian language is main)

**Comment by limpkin** [comment]
This seems to be a dead key issue: on standard keyboard layout, I can't type '^' by itself, I need to type '^' and then add a space. The Mini BLE therefore does the same. Could you let us know which layout is set on your computer when you experience that issue?

**Comment by EugeneRymarev** [comment]
> Could you let us know which layout is set on your computer when you experience that issue?

@limpkin, ENG
![image](https://user-images.githubusercontent.com/6260309/210972746-5a20e7bc-928d-4a38-952c-3bf753509d9a.png)

If I forgot to change the layout, I see this
![image](https://user-images.githubusercontent.com/6260309/210972992-125ea84c-d0b3-423e-a0e7-4effd1146cf2.png)
![image](https://user-images.githubusercontent.com/6260309/210973027-ad8e3800-84bc-4157-82a8-a03d7fe376df.png)

**Comment by limpkin** [comment]
I'm guessing this is only happening with the ^ character, but I'm not sure why a windows system is affected.
Can you confirm that when you type '^' on your keyboard it gets directly typed?

**Comment by barathrm** [comment]
> I'm guessing this is only happening with the ^ character, but I'm not sure why a windows system is affected. Can you confirm that when you type '^' on your keyboard it gets directly typed?

I guess the issue here is that the minible can't be configured with a russian layout. so it sends characters as if it was an english (?) layout, which is interpreted incorrectly by the operating system expecting a russian keyboard (and the corresponding key events).

**Comment by EugeneRymarev** [comment]
> english (?) layout

@barathrm, i have 2 layouts
1. on ENG layout i receive `^ ` with space
2. on RUS layout i receive `: ` with space

**Comment by barathrm** [comment]
> > english (?) layout
> 
> @barathrm, i have 2 layouts
> 
>     1. on ENG layout i receive `^ ` with space
> 
>     2. on RUS layout i receive `: ` with space

Yeah, but I mean on the mooltipass. The mooltipass itself is also configured with a keyboard layout to "pretend" to be a keyboard of that type and that a human presses keys on that type of layout.

I mean here, in moolticute, there is no russian layout, so it will have to pretend to be some other layout for now (and the OS layout must match):

![image](https://user-images.githubusercontent.com/76487253/212623259-a478129c-6b19-4e00-90b6-96682fada795.png)

**Comment by EugeneRymarev** [comment]
> Yeah, but I mean on the mooltipass. The mooltipass itself is also configured with a keyboard layout to "pretend" to be a keyboard of that type and that a human presses keys on that type of layout.

@barathrm, So you need to add the Russian language.

To be honest, I still do not understand what the problem is to add it at least somehow. There are a lot of ready-made fonts with the Russian language. If the problem is in the translation, then I can help.

**Comment by limpkin** [comment]
@barathrm thanks for the help!
What's odd to me is that even if @EugeneRymarev layout is configured as english, that the deadkeys behavior isn't the same as an english layout... why for the same layout the Mini shouldn't send the space?

**Comment by barathrm** [comment]
> @barathrm thanks for the help! What's odd to me is that even if @EugeneRymarev layout is configured as english, that the deadkeys behavior isn't the same as an english layout... why for the same layout the Mini shouldn't send the space?

I think it's because on many layouts, you get a `^` by press `Shift, ^, Space`. But on a russian keyboard, the ^ might have its own dedicated key, so a dead-key is not required to produce it. In that case, the fix would be to send only `Shift, ^` (or 6, if that's the keycode... I always forget/get confused by keycodes vs scan codes etc)

**Comment by limpkin** [comment]
on the french layout the ^ also gets his own key... yet i need to send the space key too :D

**Comment by limpkin** [comment]
you're correct @barathrm

**Comment by limpkin** [comment]
@EugeneRymarev is there any character that you can only type if it is followed by a space bar press?

**Comment by EugeneRymarev** [comment]
@limpkin, no

**Comment by limpkin** [comment]
how can you type â then?

**Comment by EugeneRymarev** [comment]
> how can you type â then?

@limpkin, i don't have this symbol in my layout RUS.
That is French language - i know only `Alt + NumPad 0226` for this symbol

**Comment by limpkin** [comment]
hmm... so what's the use of ^ for your english layout in that case, if you can only type it and can't combine it with anything else?

**Comment by EugeneRymarev** [comment]
@limpkin, such things are usually done by the editor in which it works, for example Word.

**Comment by limpkin** [comment]
Anyway, for this bug, when testing locally I can't replicate your issue (mooltipass layout set to english, windows layout set to english): no space character is sent.
What layout do you select in moolticute settings?

**Comment by EugeneRymarev** [comment]
@limpkin, nice. Now without space after `^` symbol.

**Comment by My1** [comment]
> @limpkin, such things are usually done by the editor in which it works, for example Word.
> 
> It seems to me that if MiniBLE emulates keyboard input, then special characters (dead keys) should be entered through Alt codes.

no thanks, iirc that only works in windows so on Linux that would be breaking stuff needlessly

**Comment by My1** [comment]
> @limpkin, nice. Now without space after `^` symbol.

makes sense, US intl has some dead keys active to specifcally be able to make international characters without needing alt codes.
