### ISSUE TITLE
Notes - on the device

### ISSUE THREAD

**Issue by sethm1** [mooltipass/minible#391]
### Justification
This I don’t get. The windows desktop app moolticute has a tab where I can add notes. BUT the note does not transfer to the device- mini BLE.  I would like to have folder on the device to store brief notes, such as passport and TSA known travel number - for traveling and when I don’t want to have it on my phone.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?
None aware of.

**Comment by gisturbance** [comment]
Already suggested [here](https://github.com/mooltipass/minible/issues/363).

**Comment by limpkin** [comment]
thanks @gisturbance !
