### ISSUE TITLE
Throw out gyro (both when no card is inserted and as an option in general)

### ISSUE THREAD

**Issue by My1** [mooltipass/minible#402]
### Missing feature
I noticed the gyro wakeup having been active while there wasnt even a card in the MP, and thought especially while it's being carried around or whatever that aside from actually waking up the device just keeping an eye on the gyro might cause some unneeded battery drain, and especially while there is no card in the MP there is literally nothing the user can do, except for putting in a card (or perhaps fully turning off the MP, which isnt a great idea anyway due to the loss of time.

so I would propose to
1) just throw out the gyro while no card is in
2) give an option for gyro stuff that could be a dropdown with 3 options:
a) active
b) disable on battery
c) always off

### Justification
Tell us why you would like to see this feature added.

less battery drain is always great

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

currently not really.

**Comment by limpkin** [comment]
The gyro wakeup only happens when the device is battery powered, I'm therefore guessing your device wakes up because the wheel gets pushed?

**Comment by My1** [comment]
I was mostly thinking of making this short suggestion (where you said good suggestion) into an issue, if the fw already does stuff to work around this cool, and can be closed.

https://matrix.to/#/!ruKpkRrOFphGsnWhet:matrix.org/$8XJTf88qBz7XSDxS3-kqKPYh8nOikfO8oX5jqanCzJE?via=libera.chat&via=matrix.org&via=van-hemmen.com

**Comment by limpkin** [comment]
It seems I was mistaken when I wrote that reply on matrix :(

**Comment by limpkin** [comment]
I'm closing this issue as the gyro isn't used when the device is on battery
