### ISSUE TITLE
Mini BLE does not scroll backwards past the start.

### ISSUE THREAD

**Issue by CGuy-1** [mooltipass/minible#404]
### Expected behavior
When selecting a credential to login manually, the device doesn't scroll backwards past the start of the DB. So for Yahoo.com, you scroll backwards to find it quickly.
### Actual behavior
The scroll stops at the start of the DB list going backwards but will scroll from the end to the start going forwards. If Yahoo.com is the last entry you are forced to scroll through all entries, if you go past you're back at the start and need to go through the list again.
### Step by step guide to reproduce the problem
Select Login, move scroll wheel to descend the list, it stops at the first entry.
### Firmware Version
AUX MCU version:  0.73
Main MCU version:  0.84
Bundle version:  12

### Moolticute Version - If Involved
N/A (v1.01.0)
### Operating System
- Windows 11

### Mooltipass Extension
N/A

**Comment by limpkin** [comment]
that's odd... could you perform an integrity check?

**Comment by CGuy-1** [comment]
How do I perform the integrity check?

**Comment by limpkin** [comment]
dedicated button in the synchronization tab :)

**Comment by CGuy-1** [comment]
Integrity check came good.
![image](https://github.com/mooltipass/minible/assets/101373127/5d6382f5-ddc8-4db6-86d3-f2bad97eccb9)

**Comment by limpkin** [comment]
can you try again now?

**Comment by CGuy-1** [comment]
Same, it won't go past the beginning of the list in reverse.

**Comment by limpkin** [comment]
in memory management mode, are you able to see passwords at the end of the credential list?

**Comment by CGuy-1** [comment]
Not at the end of the list. I need to select and press the icon in the password field and approve on the device to see the password.

I have noticed that for some accounts I never get the prompt on the device to see the password so it comes back denied. Other accounts I'm able to get the password as expected.

**Comment by CGuy-1** [comment]
The first one I found that failed was the 2nd credential of the service  **a8.com**, the first credential works correctly.
The next service, **b1.com**, has one credential and it also failed but the single credential for **a7.com** worked.
I went through the list and the 2nd credential of **m3.com** failed, the first worked correctly. The previous service, **m7.com**, has 4 credentials that all worked.

After correcting the two errors in the database, I get the prompt for every credential I've tested and the scrolling backwards past the first entry is working.

**Comment by CGuy-1** [comment]
As an aside, possibly related, I originally had two Notes, now when I check there are 6, 3 copies of each one. Is this another corruption? Do I need to manually backup the information, delete all the notes and manually recreate them?

**Comment by limpkin** [comment]
unlikely, but there was a bug quite a long time ago on moolticute that could possible duplicate notes... can you confirm you're running the latest moolticute?

**Comment by CGuy-1** [comment]
Moolticute v.1.01.0, Check for updates returns that I'm running the latest.
So I can just delete the extra notes?

What caused the corrupt DB that stopped the reverse scrolling and password display? Is there something I need to do to avoid it in the future?

**Comment by limpkin** [comment]
you may indeed... just check that the others can be read.
Your bug won't happen in the future as we fixed the underlying issue on moolticute :)
