### ISSUE TITLE
Entering recorded data regardless of system layout

### ISSUE THREAD

**Issue by EugeneRymarev** [mooltipass/minible#413]
### Expected behavior
Entering recorded data regardless of system layout. If the device contains the entry `myemail@mail.com`, then enter it that way, even if the current system layout does not match.
### Actual behavior
Instead of the expected `myemail@mail.com`, `ьнуьфшд"ьфшдюсщь` is entered on the RU layout.
### Step by step guide to reproduce the problem
1. Create a record `myemail@mail.com`
2. Set the system to the RU layout or any other that will not coincide with the layout in which the `myemail@mail.com` entry was entered
3. Change the current layout to RU (or another selected one)
4. Manually select this entry on Mooltipass and ask it to enter the data into the controlled device
### Firmware Version
AUX MCU version:  0.74
Main MCU version:  0.86
Bundle version:  13 (beta?)

### Operating System
- Windows 11
- Android 14
### Comment
I still can't understand one thing. Why is it that when a device automatically enters a login and password, it enters exactly as it is written in its memory, regardless of the current layout of the controlled device (be it a PC or a phone); and when I manually select a service and ask the device to enter a login and password, does it enter in the current layout? For example, my device enters the email `myemail@mail.com` as `ьнуьфшд"ьфшдюсщь` - that is, in the current layout of the managed device RU.

**Comment by limpkin** [comment]
We are using two different mechanisms to send credentials to the computer.
When using the extension, we are using a custom HID channel while when
recalling credentials through the device we are using a "keyboard HID"
channel.
The latter channel uses key positions and not characters (that's the HID
standard) so the mini ble needs to be aware of the keyboard layout selected
on the computer.

There's therefore no solution for your issue...

**Comment by EugeneRymarev** [comment]
@limpkin, Why can't change the manual input mechanism to imitate automatic input?

**Comment by limpkin** [comment]
For the same reason you need a keyboard to type things in your computer..,.

**Comment by EugeneRymarev** [comment]
@limpkin, I don't understand. What's the problem with using custom HID for manual entry? 🤔

**Comment by limpkin** [comment]
because your program (let's say, notepad) only "listens" to keyboard presses

**Comment by EugeneRymarev** [comment]
@limpkin, Fine. Let me pose the question a little differently.

Is such an implementation impossible or possible, but requires a lot of labor?

Something tells me that there are no unsolvable problems.

**Comment by limpkin** [comment]
I don't think it's actually doable to have a software simulate key presses
into any open program... but I may be wrong

**Comment by EugeneRymarev** [comment]
@limpkin, check Clickermann. That tool from russian developer.
[Direct download link](http://crapware.aidf.org/files/9/)
[Main page](http://crapware.aidf.org/page/clickermann)

**Comment by limpkin** [comment]
I'm sorry, I don't speak russian.
I'm going to close this issue for now as implementing the feature you're requesting requires an external program that could directly requests credentials to the mini BLE.

**Comment by EugeneRymarev** [comment]
@limpkin, The program includes English. The site can be translated using the built-in translator in the browser. In any case, this is just an example that this is possible.

I can (if I read the documentation) write a simple Python script that will enter any information in any language into any window.

Why need new external program if you already have Moolticute?

**Comment by limpkin** [comment]
right... it sounds like a feature request for moolticute then :)
