### ISSUE TITLE
BUG: Unable to save password when a category is selected & PIN for MMM is off

### ISSUE THREAD

**Issue by xWTF** [mooltipass/minible#419]
### Expected behavior
Be able to save (update) password of credentials after entering MMM fron any state.

### Actual behavior
Save fails with "Couldn't change all passwords, please approve prompts on the defice" error message, and the password is not saved.

### Step by step guide to reproduce the problem
1. Turn off **PIN for MMM** in **Settings** page on device
2. Select **Category [hashtag]1** in **Set Active Category** page on device
3. Enter MMM
4. Try to update password or add new credentials from Moolticute
5. It fails ¯\\\_(ツ)\_/¯

Here's the reproduce video with emulator built from aecd397 on Ubuntu 22.04.3:
https://github.com/mooltipass/minible/assets/31540475/c7b542aa-6090-4726-a442-742bcf944ccb

### Firmware Version
Bundle version: v12 and v13 from official firmware fetcher
Also reproducible in commit aecd397.

### Moolticute Version - If Involved
v1.03.0 official release

### Operating System
- Ubuntu 22.04.3
- Windows 10 21H2
- I believe it's OS independent.

### Mooltipass Extension
N/A

**Comment by limpkin** [comment]
@xWTF that's a very neat find... I'm surprised it actually took so long to get reported!
