### ISSUE TITLE
Replacement with new battery does not work unplugged

### ISSUE THREAD

**Issue by ConYel** [mooltipass/minible#422]
### Expected behavior
Replace the battery and minible works unplugged.
### Actual behavior
Battery replaced but it doesn't work unplugged
### Step by step guide to reproduce the problem
?replace the battery with  a new one?
### Firmware Version
AUX MCU version:  0.66
Main MCU version:  0.77
Bundle version: v5 

### Operating System
- Debian Based distribution

Is there any hardware reset (security feature?) regarding the battery replacement that I haven't checked and needs to be done after the replacement?

**Comment by limpkin** [comment]
hello, sorry for my delayed answer... did you manage to fix your issue?

**Comment by ConYel** [comment]
Yeap, the new battery wasn't actually new so it had to be replaced by the manufacturer.
