### ISSUE TITLE
Battery seems to be dying and support is not responding

### ISSUE THREAD

**Issue by KingWarin** [mooltipass/minible#424]
### Expected behavior
Battery holds charge or holds charge after reload / reconditioning
Answer or at least acknowledgement of mails sent via contact form and support mail. 

### Actual behavior
Devices turns off after removing card, even if it was fully recharged (or reconditioned) just before - already described the behavior in detail twice, once when sending a message using the contact form on the website two weeks ago, a second time when sending a mail to the support mail address one week ago. Unfortunately no reaction so far.

I really don't know what the problem is, but I'd expect a device at this price point to function for a longer period than one year, even under heavy, daily useage. Or at least to get responses from support when a problem is reported (even a response that says there is no more support after passing one year would be better than no reaction at all).

### Step by step guide to reproduce the problem
I doubt there is a good step by step guide as this seems like a hardware issue

### Firmware Version
AUX MCU version:  0.74
Main MCU version:  0.86
Bundle version:  13

### Moolticute Version - If Involved
v1.03.0

### Operating System
Mention if you are using either:
Debian

**Comment by limpkin** [comment]
Hello!
Our sincere apologies - we were on holidays last week and have just answered your email to kickstart the debugging process.
I'm going to close this issue as this is the firmware repository and not the hardware one (minible_hw).
