### ISSUE TITLE
sending username/password with both connections under OS X

### ISSUE THREAD

**Issue by mpble** [mooltipass/minible#44]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Insert username, password at the desired position.
### Actual behavior
nothing inserted at the desired position.
### Step by step guide to reproduce the problem
- Connect Mooltipass BLE and MacBook Pro with a USB cable
- Connect Mooltipass BLE and MacBook Pro with bluetooth

### Moolticute Version - If Involved
0.42.9
### Operating System
MacBook Pro Model 2017, MacOS Catalina (10.15.1)
Mention if you are using either:
- Windows 7/10
- Debian Based distribution
- Other Linux distribution
- MacOS  
  
Other operating systems are not supported.

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
looking at your other issues, i'm confused: are your credentials being output or not at all?
or they're not output when you don't set any delay?
