### ISSUE TITLE
insert username with keyboard setting German (Mac OS)

### ISSUE THREAD

**Issue by mpble** [mooltipass/minible#45]
Use one of the two templates below and delete the other. All issues not following this template will be directly closed.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
"xxx.yyy@domain.com" will be entered
### Actual behavior
"ttt+uuu<´ki]ej+_ki" is entered

### Step by step guide to reproduce the problem
- select tab Device Settings
- select "USB Keyboard Layout" German(MacOS)
- press "Save to device"
- enter field on MacBook Pro, where you want to insert the usernam (login)
- select Login on Mooltipass BLE
- confirm
### Operating System
Mention if you are using either:
- Windows 7/10
- Debian Based distribution
- Other Linux distribution
- MacOS  
  
Other operating systems are not supported.

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
can you enable the advanced menu, and confirm inside the settings menu that german layout is correctly selected?
