### ISSUE TITLE
insert username with Germany keyboard (non MAC)

### ISSUE THREAD

**Issue by mpble** [mooltipass/minible#46]
8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
"xxx.yyy@domain.com" will be entered
### Actual behavior
"xxx.yyy«domain.com" is entered

### Step by step guide to reproduce the problem
- select tab Device Settings
- select "USB Keyboard Layout" Germany
- press "Save to device"
- enter field on MacBook Pro, where you want to insert the usernam (login)
- select Login on Mooltipass BLE
- confirm
### Operating System
MacBook Pro, Model 2017, MacOS Catalina (10.15.1)
Mention if you are using either:
- Windows 7/10
- Debian Based distribution
- Other Linux distribution
- MacOS  
  
Other operating systems are not supported.

### Mooltipass Extension
- If you're creating an issue to report a website incompatibility, please use the "Report incompatibilities with this website" item in the extension menu.
- If you're creating an issue to report a problem with our extension, please create another issue here: 
https://github.com/mooltipass/extension/issues

8<------------------------ END BUG REPORT -------------------------------------

**Comment by limpkin** [comment]
but if you're using a Mac... should you try german (MacOS)?
