### ISSUE TITLE
Lock the device when disconnects from computer.

### ISSUE THREAD

**Issue by WebmasterTD** [mooltipass/minible#47]
### Missing feature

Feature to automatically lock the BLE device whenever it disconnects from a computer or host. 
Maybe even an optional timeout.

### Justification

It would be easier for the user, by not having to manually lock the device every time its unplugged or disconnected.

**Comment by limpkin** [comment]
agreed... I'll make it a settings

**Comment by limpkin** [comment]
implemented in 04d08e3667bc3fcf2c9ec04f606c98b5aa2073b0
