### ISSUE TITLE
Charging animation doesn't stop when full

### ISSUE THREAD

**Issue by arieljt** [mooltipass/minible#58]
### Expected behavior
Once Mooltipass BLE battery is full, the charging animation should show a full battery so the user knows that battery is fully charged.

### Actual behavior
The battery animation shows charging as long as the device is connected.

### Step by step guide to reproduce the problem
Connect your Mooltipass BLE to a computer.

### Moolticute Version
N/A

### Operating System
N/A

### Mooltipass Device
- The Mooltipass Mini BLE

**Comment by arieljt** [comment]
Aux MCU version: 0.10
Main MCU version: 0.11

**Comment by arieljt** [comment]
Seems that Main MCU 0.12 fixed the issue

**Comment by limpkin** [comment]
woot!
