### ISSUE TITLE
Lock device on PC shutdown

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#59]
### Missing feature
Lock the Mooltipass Mini BLE during PC shutdown
### Justification
If I'm in a rush it happens that I forget to pull out the smartcard. But I always shutdown my PC.

### Workarounds
Don't forget to pull out the smartcard.

**Comment by ThunderKing54** [comment]
Thanks Mathieu 👍

**Comment by limpkin** [comment]
sure :)
