### ISSUE TITLE
Mooltipass Mini BLE crashes/weired screen

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#74]
### Expected behavior
Mooltipass Mini BLE shouldn't crash/show weired screen content if you stop entering the PIN and wait until the device enters sleep mode. 

### Actual behavior
If you select the first number of your PIN code and wait until the Mooltipass enters sleep mode it start crashing or the screen is cutted in half. 

### Step by step guide to reproduce the problem
1) Enter your smartcard into the Mooltipass
2) Connect the Mooltipass with your PC
3) Select a random number for the first PIN but don't press the scroll wheel
4) wait until the Mooltipass enters sleep mode
5) Use the scroll wheel to wake up the mooltipass again.
6) The screen is cutted in half and only shows half of the content
![testb](https://user-images.githubusercontent.com/58223763/74631710-e8eee480-515d-11ea-9036-2eb3102279c8.jpg)

### Moolticute Version - If Involved
v0.42.31-testing

### Firmware Version
AUX MCU version:  0.13
Main MCU version:  0.18

### Operating System
- Windows 10 Enterprise 2016 LTSB

**Comment by limpkin** [comment]
this is an awesome find. thanks for the bug report!
