### ISSUE TITLE
Windows / Firefox / webauthn.me : 2 prompts when getting assertion data

### ISSUE THREAD

**Issue by limpkin** [mooltipass/minible#76]
on webauthn.me, simply register a new credential then follow the process to get authenticated: you'll get 2 prompts on the device

**Comment by 0x0ptr** [comment]
There should be at least two prompts. One for confirming creation of a new credential and one for the actual authentication (get assertion). Do you see more than those two?

**Comment by limpkin** [comment]
i get two prompts for the assertion actually....

**Comment by WebmasterTD** [comment]
I also got two prompts when testing on chrome.
