### ISSUE TITLE
ctap.c: uknown error

### ISSUE THREAD

**Issue by limpkin** [mooltipass/minible#77]
... when denying user registration prompt

Main->Aux:        FIDO2 Message - missing command description: 4
Debug MSG:                                CborError: 0x27: ../src/fido2/ctap.c: 572: unknown error
Debug MSG:                                make_credential time: 40802 ms
Debug MSG:                                DATA [len: 0]
Debug MSG:                                [000]:
Debug MSG:                                cbor output structure: 0 bytes.  Return 0x27
Debug MSG:                                CBOR writeback: 40805 ms
Debug MSG:
Debug MSG:                                  length: 8
Debug MSG:                                adding a new cid
Debug MSG:                                  length: 1
Debug MSG:                                CTAPHID_CBOR
Debug MSG:                                cbor input structure: 0 bytes
Debug MSG:                                cbor req:
Debug MSG:                                DATA [len: 0]
Debug MSG:                                [000]:
Debug MSG:                                CTAP_GET_INFO
Debug MSG:                                DATA [len: 54]
Debug MSG:                                [000]: A4 01 81 68 46 49 44 4F 5F 32 5F 30 03 50 6D B0
Debug MSG:                                [010]: 42 D0 61 AF 40 4C A8 87 E7 2E 09 BA 7E B4 04 A4
Debug MSG:                                [020]: 62 72 6B F5 62 75 70 F5 62 75 76 F5 64 70 6C 61
Debug MSG:                                [030]: 74 F4 05 19 04 00
Debug MSG:                                cbor output structure: 54 bytes.  Return 0x00
Debug MSG:                                CBOR writeback: 59379 ms

**Comment by 0x0ptr** [comment]
https://github.com/mooltipass/minible/pull/82
