### ISSUE TITLE
Accept/deny credential selection and animation

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#78]
### Expected behavior
If you have to select between deny and accept a credential you can scroll down and up. It should stay at the selected deny field if you constantly scroll down. If you scroll up the 🡹 arrow should flash. If you scroll down the 🡻 arrow should flash.

### Actual behavior
If you have to select between deny and accept a credential you can scroll down and up, If you keep scrolling down it switches between accept and deny. Even the animation is the wrong way around. If I scroll up the arrow 🡻 start flashing.

### Step by step guide to reproduce the problem
1) enter your smartcard and type in your pin(Animation is fine)
2) go to the Login menu and press the scroll wheel.
3) select one website and press the scroll wheel.
4) if the prompt ask if you want to login with the account scroll down.
5) the upper arrow starts flashing but you scroll down

### Firmware Version
AUX MCU version:  0.13
Main MCU version:  0.18

### Operating System
- Windows 10 Enterprise 2016 LTSB

**Comment by limpkin** [comment]
Thanks for the great report!  
I pushed a fix for the animation issue, but I'm not sure to agree with you that continuing to scroll down should keep the deny option selected... but feel free to reopen an issue for this.
