### ISSUE TITLE
Stack tracking function call

### ISSUE THREAD

**Issue by limpkin** [mooltipass/minible#81]
I apologize in advance @0x0ptr ....

It just occurred to me that it doesn't make sense adding the call to main_init_stack_tracking in both bootloaders, as we can't update the bootloaders of the currently deployed units (and the ones currently being produced...).

If I'm not mistaken, we should therefore:
- remove all stack tracking code from bootloaders
- move the main_init_stack_tracking call in the main/aux solutions from jump_to_application_function to the first line after the main()

Due to the time the call to main_init_stack_tracking may take it may be worth moving out platform_io_enable_switch() call from main_platform_init() to before the call to main_init_stack_tracking on the main solution

is it an issue if we corrupt the stack if we're never returning to jump_to_application_function() ?

**Comment by 0x0ptr** [comment]
https://github.com/mooltipass/minible/pull/83
