### ISSUE TITLE
Mooltipass freeze after disconnect during Animation

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#84]
### Expected behavior
If I unplug the Mooltipass during the message "No Stored Favorites" the animation icon should stay and return to the main menu.
### Actual behavior
If I unplug the Mooltipass during the message "No Stored Favorites" the Mooltipass freeze and the icon animation is visible on the main menu. I can't switch through the menu until I remove the 
smartcard
https://www.youtube.com/watch?v=AUE0TKxQsc8

### Step by step guide to reproduce the problem
1) connect your MPM BLE with USB-c
2) insert the smartcard and enter your pin
3) go to the "Favorites" menu icon and press the scroll wheel
4) disconnect the Mooltipass when the message "No Stored Favorites" appear.
5) your able to see the animation icon on the main menu. You can't scroll through the menu it seems like the Mooltipass is frozen.

### Firmware Version
AUX MCU version:  0.14
Main MCU version:  0.19

### Operating System
Mention if you are using either:
- Windows 10 Enterprise 2016 LTSB

**Comment by limpkin** [comment]
that's.... quite amusing indeed!
