### ISSUE TITLE
(small bug) Animation keep going after disconnect 

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#90]
### Expected behavior
If you disconnect your Mooltipass inside the "No stored Favorites" animation, the animation should stop after 3-4 seconds like when you leave it connected. 
### Actual behavior
If you disconnect your Mooltipass from USB during the "No stored Favorites" animation, the animation is visible until you press the scroll wheel.
### Step by step guide to reproduce the problem
1) insert your smartcard and enter pin
2) go to Favorites menu and press enter
3) if you don't have any favorites it should display the message "No stored Favorites"
4) disconnect the mooltipass
5) the message is stillt here until you press the scroll wheel.

### Firmware Version
AUX MCU version:  0.16
Main MCU version:  0.20

### Operating System
- Windows 10 Pro 18362

**Comment by limpkin** [comment]
always a pleasure finding and fixing the bugs you find :)
