### ISSUE TITLE
battery "empty" when unplugging the mooltipass 

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#94]
I found another battery bug ;D
### Expected behavior
If you disconnect your mooltipass more than twenty times in less then 7 seconds it should show the right battery value.
### Actual behavior
If you disconnect your mooltipass multiple times very fast the batteryindicator shows that the battery is empty
### Step by step guide to reproduce the problem
1) plug and unplug your mooltipass with usb over twenty times
2) insert smartcard and enter pin
3) the batteryindicator now shows a empty battery

### Firmware Version
AUX MCU version:  0.17
Main MCU version:  0.21

### Operating System
Mention if you are using either:
- Windows 10 Pro

**Comment by limpkin** [comment]
twenty times xD 

looking into it :), nice find!

**Comment by limpkin** [comment]
when you do this, is your battery initially full or discharged?

**Comment by ThunderKing54** [comment]
It is full and I do it pretty fast.

**Comment by limpkin** [comment]
[bundle.zip](https://github.com/mooltipass/minible/files/4396071/bundle.zip)

Could you try this firmware and let me know if that helps? I can't reproduce the bug so it makes things a bit tricky...

**Comment by ThunderKing54** [comment]
I test it a bit

**Comment by limpkin** [comment]
is this issue fixed? :)

**Comment by ThunderKing54** [comment]
I think it is :). Thank you 👍
