### ISSUE TITLE
When bluetooth connected, does not lock on computer shutdown

### ISSUE THREAD

**Issue by elendil-software** [mooltipass/minible#97]
## Expected behavior

When the computer is powered off the Mooltipass should be locked
 
### Actual behavior

With Mooltipass connected with Bluetooth, on computer shutdown, the Mooltipass is not locked

### Step by step guide to reproduce the problem

1. Connect the Moltipass with Bluetooth and not USB
2. Shutdown the computer
3. The Mooltipass is not locked

### Moolticute Version

v0.43.9

### Firmware Version
AUX MCU version:  0.18
Main MCU version:  0.22

### Operating System
Mention if you are using either:
- Windows 10

**Comment by limpkin** [comment]
awesome find! thanks a lot!!!!
