### ISSUE TITLE
Database Management stuck after disconnect

### ISSUE THREAD

**Issue by ThunderKing54** [mooltipass/minible#98]
### Expected behavior
If you unplug your mooltipass during the "Database Management" and if bluetooth is disabled the Database Management should stop and return to the main menu.
### Actual behavior
If you unplug your mooltipass during the "Database Management" it is "stuck" inside that animation.
### Step by step guide to reproduce the problem
1) enter your smartcard and pin
2) click on "Enter Credentials Management Mode" in Moolticute
3) enter your smartcard pin again
4) unplug the mooltipas
5) The "Database Management" animation and message is still displayed. You can't press the scroll wheel. You have to plug in the usb cable or remove the smartcard. 

### Firmware Version
AUX MCU version:  0.18
Main MCU version:  0.22

### Operating System
- Windows 10 Pro

**Comment by limpkin** [comment]
how you can find these bugs will always impress me...
